const TODO_ACTION_TYPES = {
	SET_TODO: 'SET_TODO',
	SET_TODO_BEGIN: 'SET_TODO_BEGIN',
	SET_TODO_FINISH: 'SET_TODO_FINISH',
	SET_TODO_ERROR: 'SET_TODO_ERROR',
	SET_SELECTED_TODO: 'SET_SELECTED_TODO',
};

export default TODO_ACTION_TYPES;
